"{\
	'general':\
	{\
		'name':'Device',\
		'instance':1,\
		'interval':2000\
	},\
	'components':[\
    {\
      'name':'Neopixel',\
      'params':[false, true, false]\
    },\
    {\
      'name':'RFID',\
      'params':'default'\
    },\
		{\
			'name':'WiFi',\
			'params':['garden-wifi-name','garden-wifi-password']\
		}\
	]\
}"
