"{\
  'general':\
    {\
      'device_name':'Device',\
      'family':'Loom',\
      'instance_num':1,\
      'family_num':0\
    },\
  'components':\
  [\
    {\
      'name':'DS3231',\
      'params':[11,true]\
    },\
    {\
      'name':'Interrupt_Manager',\
      'params':[0]\
    },\
    {\
      'name':'Sleep_Manager',\
      'params':[true,false,1]\
    }\
  ]\
}"
