"{\
	'general':\
	{\
		'device_name':'Device',\
		'family':'Loom',\
		'instance_num':1,\
		'family_num':0\
	},\
	'components':[\
		{\
			'name':'Loom_DS3231',\
			'parameters':['DS3231',11,false,false,6]\
		},\
		{\
			'name':'Loom_Interrupt_Manager',\
			'parameters':['Interrupt-Manager',0]},\
		{\
			'name':'Loom_Sleep_Manager',\
			'parameters':['Sleep-Manager',true,false,1,19]\
		},\
		{\
			'name':'Loom_Analog',\
			'parameters':['Analog',8,12,true,true,false,false,false,false,7,4,0,0,0,0]\
		},\
		{\
			'name':'Loom_SD',\
			'parameters':['SD',true,1000,4,'data19.csv']\
		},\
		{\
			'name':'Loom_MS5803',\
			'parameters':[119,'MS5803']\
		}\
	]\
}"
