"{\
	'general':\
	{\
		'name':'Device',\
		'instance':1\
	},\
	'components':[\
		{\
			'name':'Analog',\
			'params':[8,12,true,false,true,false,false,false,5,0,4,0,0,0]\
		},\
		{\
			'name':'SD',\
			'params': [true,1000,10,'data',true]\
		},\
		{\
			'name':'DS3231',\
			'params':[11, true]\
		},\
		{\
			'name':'Interrupt_Manager',\
			'params':'default'\
		},\
		{\
			'name':'Sleep_Manager',\
			'params':[true,false,1]\
		},\
    {\
      'name':'MS5803',\
      'params':[119]\
    }\
	]\
}"
