"{\
	'general':\
	{\
		'device_name':'Device',\
		'family':'Loom',\
		'instance_num':1,\
		'family_num':0\
	},\
	'components':[\
		{\
			'name':'Loom_Analog',\
			'parameters':[\
				'Analog',\
				8,\
				12,\
				true,\
				true,\
				true,\
				true,\
				true,\
				true,\
				0,\
				0,\
				0,\
				0,\
				0,\
				0\
			]\
		},\
		{\
			'name':'Loom_Digital',\
			'parameters':[\
				'Digital',\
				true,\
				true,\
				false,\
				false,\
				false,\
				false,\
				false,\
				false,\
				false,\
				false,\
				false,\
				false\
			]\
		},\
    {\
      'name':'Loom_Ethernet',\
      'parameters':[\
        'Ether1',\
        [<your-mac-address>],\
        [192,168,0,1]\
      ]\
    },\
    {\
      'name':'Loom_DS3231',\
      'parameters':[\
        'RTC1',\
        12,\
        true,\
        false,\
        6\
       ]\
    },\
    {\
      'name':'Loom_NTP_Sync',\
      'parameters':[\
        'NTP1',\
        0,\
        0\
       ]\
    },\
    {\
      'name':'Loom_GoogleSheets',\
      'parameters':[\
        'Goog',\
        0,\
        '/macros/s/<your-url>/exec',\
        '<your-sheet-id',\
        '<your-Tab-id>',\
        '<your-device-id>'\
       ]\
    },\
		{\
			'name':'Loom_Interrupt_Manager',\
			'parameters':[\
				'Interrupt-Manager',\
				0\
			]\
		}\
	]\
}"