general:
  name: Device
  instance: 1
  interval: 500
components:
  - name: Analog
  - name: Digital
  - name: WiFi
    params:
      - <ssid>
      - <password>
  - name: MaxPub
    params:
      - 7002
  - name: MaxSub
    params:
      - 7002
      - true
