general:
  name: Device
  instance: 1
  interval: 5000
  print_verbosity: 2
components:
  - name: SD
  - name: DS3231
  - name: InterruptManager
    params:
      - 0
  - name: SleepManager
    params:
      - true
      - false
      - 1
  - name: LTE
    params:
      - <apn>
      - <username>
      - <password>
      - <analog_pin>
  - name: GoogleSheets
    params:
      - Goog
      - 7003
      - /macros/s/<your-script-id>/exec
      - <your-sheet-id>
      - true
      - <your-tab-name>
